### ISSUE TITLE
Where is the fullwiki_input_improved_by_cogqa1hop.zip?

### ISSUE THREAD

**Issue by JerryZeyu** [THUDM/CogQA#7]
I have completed training the task1 and task2. When I want to evaluate the model, I couldn't find where is the fullwiki_input_improved_by_cogqa1hop.zip. So I directly run the command: python cogqa.py --data_file='hotpot_dev_fullwiki_v1_merge.json'. But during the answering, it shows some wrong: ValueError: attempt to get argmin of an empty sequence. 
Start Training... on 1 GPUs
 17%|██████▊                                | 1294/7405 [03:41<13:29,  7.55it/s]Traceback (most recent call last):
  File "cogqa.py", line 244, in <module>
    fire.Fire(main)
  File "/home/zeyuzhang/anaconda3/lib/python3.7/site-packages/fire/core.py", line 127, in Fire
    component_trace = _Fire(component, args, context, name)
  File "/home/zeyuzhang/anaconda3/lib/python3.7/site-packages/fire/core.py", line 366, in _Fire
    component, remaining_args)
  File "/home/zeyuzhang/anaconda3/lib/python3.7/site-packages/fire/core.py", line 542, in _CallCallable
    result = fn(*varargs, **kwargs)
  File "cogqa.py", line 234, in main
    gold, ans, graph_ret, ans_nodes = cognitive_graph_propagate(tokenizer, data, model1, model2, device, setting = setting, max_new_nodes=max_new_nodes)
  File "cogqa.py", line 147, in cognitive_graph_propagate
    l, r = find_start_end_before_tokenized(orig_text, [pred_slice])[0]
  File "/home/zeyuzhang/Downloads/CogQA-master/utils.py", line 238, in find_start_end_before_tokenized
    result = fuzzy_find([span], orig_text)
  File "/home/zeyuzhang/Downloads/CogQA-master/utils.py", line 107, in fuzzy_find
    r, score = dp(item, sentence)
  File "/home/zeyuzhang/Downloads/CogQA-master/utils.py", line 86, in dp
    r = np.argmin(f[len(a) - 1])
  File "/home/zeyuzhang/anaconda3/lib/python3.7/site-packages/numpy/core/fromnumeric.py", line 1172, in argmin
    return _wrapfunc(a, 'argmin', axis=axis, out=out)
  File "/home/zeyuzhang/anaconda3/lib/python3.7/site-packages/numpy/core/fromnumeric.py", line 56, in _wrapfunc
    return getattr(obj, method)(*args, **kwds)
ValueError: attempt to get argmin of an empty sequence
Can you tell me how to solve these? Thank you very much.

**Comment by Sleepychord** [comment]
Hi, I am sorry for the typos. I have fixed it.

**Comment by JerryZeyu** [comment]
When I run the command: python cogqa.py --data_file='hotpot_dev_fullwiki_v1_merge.json'. But during the answering, it shows some wrong: ValueError: attempt to get argmin of an empty sequence.
Start Training... on 1 GPUs
17%|██████▊ | 1294/7405 [03:41<13:29, 7.55it/s]Traceback (most recent call last):
File "cogqa.py", line 244, in 
fire.Fire(main)
File "/home/zeyuzhang/anaconda3/lib/python3.7/site-packages/fire/core.py", line 127, in Fire
component_trace = _Fire(component, args, context, name)
File "/home/zeyuzhang/anaconda3/lib/python3.7/site-packages/fire/core.py", line 366, in _Fire
component, remaining_args)
File "/home/zeyuzhang/anaconda3/lib/python3.7/site-packages/fire/core.py", line 542, in _CallCallable
result = fn(*varargs, **kwargs)
File "cogqa.py", line 234, in main
gold, ans, graph_ret, ans_nodes = cognitive_graph_propagate(tokenizer, data, model1, model2, device, setting = setting, max_new_nodes=max_new_nodes)
File "cogqa.py", line 147, in cognitive_graph_propagate
l, r = find_start_end_before_tokenized(orig_text, [pred_slice])[0]
File "/home/zeyuzhang/Downloads/CogQA-master/utils.py", line 238, in find_start_end_before_tokenized
result = fuzzy_find([span], orig_text)
File "/home/zeyuzhang/Downloads/CogQA-master/utils.py", line 107, in fuzzy_find
r, score = dp(item, sentence)
File "/home/zeyuzhang/Downloads/CogQA-master/utils.py", line 86, in dp
r = np.argmin(f[len(a) - 1])
File "/home/zeyuzhang/anaconda3/lib/python3.7/site-packages/numpy/core/fromnumeric.py", line 1172, in argmin
return _wrapfunc(a, 'argmin', axis=axis, out=out)
File "/home/zeyuzhang/anaconda3/lib/python3.7/site-packages/numpy/core/fromnumeric.py", line 56, in _wrapfunc
return getattr(obj, method)(*args, **kwds)
ValueError: attempt to get argmin of an empty sequence
Can you tell me how to solve these? Thank you very much.

**Comment by qibinc** [comment]
@JerryZeyu unzip `improved_retrieval.zip`
